version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.yaml:/var/jenkins_home/casc.yaml
      - .:/var/jenkins_home/workspace/flask-app
      - ./Jenkinsfile:/var/jenkins_home/workspace/flask-app/Jenkinsfile
    environment:
      - JENKINS_JAVA_OPTS=-Xmx2g -Djava.awt.headless=true
      - JENKINS_UC_DOWNLOAD=https://updates.jenkins.io/download
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    command: >
      bash -c "apt-get update &&
      apt-get install -y python3 python3-pip python3-venv &&
      curl -L 'https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64' -o /usr/local/bin/docker-compose &&
      chmod +x /usr/local/bin/docker-compose &&
      /usr/local/bin/jenkins.sh"
    depends_on:
      - web

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

volumes:
  jenkins_home: 